"""公开 ZNIKU 0.2.0 最小 Runtime 模型、调度、执行与持久化接口。

该命名空间只提供普通 Run/NodeRun/Artifact/NodeResult、同步 Scheduler、Node Runner 与 Project
orchestration；不导出 0.1.0 Runtime、Compiler、Evidence、digest、checkpoint 或 resume 语义。
"""

from .models import (
    Artifact,
    ExternalHandoff,
    ExternalOutputTarget,
    FailureReason,
    FrameRange,
    LatestNodeResult,
    NodeResult,
    NodeRun,
    NodeRunState,
    Run,
    RunState,
    RuntimeFailure,
    StaleReason,
    new_runtime_id,
    utc_now,
)
from .repository import (
    RuntimeConflictError,
    RuntimeDataError,
    RuntimeNotFoundError,
    RuntimeRepository,
    RuntimeRepositoryError,
)
from .reuse import (
    InputEdgeSignature,
    NodeReuseSignature,
    ReuseBlockReason,
    ReuseCandidate,
    ReuseDecision,
    StaleAnalysis,
    StaleNode,
    analyze_reuse,
    analyze_stale,
    capture_node_signature,
)
from .reuse import (
    StaleReason as ReuseStaleReason,
)
from .runner import (
    HandoffInput,
    HandoffOutput,
    ManualHandoff,
    ManualSubmission,
    NodeExecutionRequest,
    NodeRunner,
    NodeValidator,
    NodeValidatorContext,
    NodeValidatorResult,
    OutputPathSpec,
    ProducedOutput,
    PythonAdapter,
    PythonAdapterContext,
    PythonAdapterResult,
    RunnerArtifact,
    RunnerCancelled,
    RunnerError,
    RunnerFailureReason,
    RunnerInput,
    RunnerInterrupted,
    RunnerResult,
)
from .scheduler import (
    InstantNodeState,
    ScheduleAnalysis,
    ScheduledNode,
    Scheduler,
    SchedulerError,
)
from .service import ArtifactQuickProbe, RuntimeService, RuntimeServiceError

__all__ = [
    "Artifact",
    "ArtifactQuickProbe",
    "ExternalHandoff",
    "ExternalOutputTarget",
    "FailureReason",
    "FrameRange",
    "HandoffInput",
    "HandoffOutput",
    "InputEdgeSignature",
    "InstantNodeState",
    "LatestNodeResult",
    "ManualHandoff",
    "ManualSubmission",
    "NodeExecutionRequest",
    "NodeResult",
    "NodeReuseSignature",
    "NodeRun",
    "NodeRunState",
    "NodeRunner",
    "NodeValidator",
    "NodeValidatorContext",
    "NodeValidatorResult",
    "OutputPathSpec",
    "ProducedOutput",
    "PythonAdapter",
    "PythonAdapterContext",
    "PythonAdapterResult",
    "ReuseBlockReason",
    "ReuseCandidate",
    "ReuseDecision",
    "ReuseStaleReason",
    "Run",
    "RunState",
    "RunnerArtifact",
    "RunnerCancelled",
    "RunnerError",
    "RunnerFailureReason",
    "RunnerInput",
    "RunnerInterrupted",
    "RunnerResult",
    "RuntimeConflictError",
    "RuntimeDataError",
    "RuntimeFailure",
    "RuntimeNotFoundError",
    "RuntimeRepository",
    "RuntimeRepositoryError",
    "RuntimeService",
    "RuntimeServiceError",
    "ScheduleAnalysis",
    "ScheduledNode",
    "Scheduler",
    "SchedulerError",
    "StaleAnalysis",
    "StaleNode",
    "StaleReason",
    "analyze_reuse",
    "analyze_stale",
    "capture_node_signature",
    "new_runtime_id",
    "utc_now",
]
